import './main.css';
import type { Metadata } from 'next';
import { GNB } from '@/widgets/gnb';
import Provider from '../providers/Providers';
import { Footer } from '@/widgets/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Provider>
          <GNB />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
