/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  rest
} from 'msw'

export const getCreateArticleFavoriteMock = () => ({article: {slug: faker.random.word(), title: faker.random.word(), description: faker.random.word(), body: faker.random.word(), tagList: Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.random.word())), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.datatype.number({min: undefined, max: undefined}), author: {username: faker.random.word(), bio: faker.random.word(), image: faker.random.word(), following: faker.datatype.boolean()}}})

export const getDeleteArticleFavoriteMock = () => ({article: {slug: faker.random.word(), title: faker.random.word(), description: faker.random.word(), body: faker.random.word(), tagList: Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.random.word())), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.datatype.number({min: undefined, max: undefined}), author: {username: faker.random.word(), bio: faker.random.word(), image: faker.random.word(), following: faker.datatype.boolean()}}})

export const getFavoritesMSW = () => [
rest.post('*/articles/:slug/favorite', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getCreateArticleFavoriteMock()),
        )
      }),rest.delete('*/articles/:slug/favorite', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getDeleteArticleFavoriteMock()),
        )
      }),]
