/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import type { NewArticle } from './newArticle';

export interface NewArticleRequest {
  article: NewArticle;
}
