/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */

export interface Profile {
  username: string;
  bio: string;
  image: string;
  following: boolean;
}
