/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from '../../mutator/custom-instance';

import type {
  LoginUserRequest,
  NewUserRequest,
  UpdateUserRequest,
  UserResponse,
} from '../../models';




/**
 * Login for existing user
 * @summary Existing user login
 */
export const login = (loginUserRequest: LoginUserRequest) => {
  return customInstance<UserResponse>({
    url: `/users/login`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: loginUserRequest,
  });
};
/**
 * Register a new user
 * @summary Register a new user
 */
export const createUser = (newUserRequest: NewUserRequest) => {
  return customInstance<UserResponse>({
    url: `/users`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: newUserRequest,
  });
};
/**
 * Gets the currently logged-in user
 * @summary Get current user
 */
export const getCurrentUser = () => {
  return customInstance<UserResponse>({ url: `/user`, method: 'get' });
};
/**
 * Updated user information for current user
 * @summary Update current user
 */
export const updateCurrentUser = (updateUserRequest: UpdateUserRequest) => {
  return customInstance<UserResponse>({
    url: `/user`,
    method: 'put',
    headers: { 'Content-Type': 'application/json' },
    data: updateUserRequest,
  });
};
