/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  rest
} from 'msw'

export const getGetArticlesFeedMock = () => ({articles: Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({slug: faker.random.word(), title: faker.random.word(), description: faker.random.word(), body: faker.random.word(), tagList: Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.random.word())), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.datatype.number({min: undefined, max: undefined}), author: {username: faker.random.word(), bio: faker.random.word(), image: faker.random.word(), following: faker.datatype.boolean()}})), articlesCount: faker.datatype.number({min: undefined, max: undefined})})

export const getGetArticlesMock = () => ({articles: Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({slug: faker.random.word(), title: faker.random.word(), description: faker.random.word(), body: faker.random.word(), tagList: Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.random.word())), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.datatype.number({min: undefined, max: undefined}), author: {username: faker.random.word(), bio: faker.random.word(), image: faker.random.word(), following: faker.datatype.boolean()}})), articlesCount: faker.datatype.number({min: undefined, max: undefined})})

export const getCreateArticleMock = () => ({article: {slug: faker.random.word(), title: faker.random.word(), description: faker.random.word(), body: faker.random.word(), tagList: Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.random.word())), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.datatype.number({min: undefined, max: undefined}), author: {username: faker.random.word(), bio: faker.random.word(), image: faker.random.word(), following: faker.datatype.boolean()}}})

export const getGetArticleMock = () => ({article: {slug: faker.random.word(), title: faker.random.word(), description: faker.random.word(), body: faker.random.word(), tagList: Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.random.word())), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.datatype.number({min: undefined, max: undefined}), author: {username: faker.random.word(), bio: faker.random.word(), image: faker.random.word(), following: faker.datatype.boolean()}}})

export const getUpdateArticleMock = () => ({article: {slug: faker.random.word(), title: faker.random.word(), description: faker.random.word(), body: faker.random.word(), tagList: Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.random.word())), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.datatype.number({min: undefined, max: undefined}), author: {username: faker.random.word(), bio: faker.random.word(), image: faker.random.word(), following: faker.datatype.boolean()}}})

export const getArticlesMSW = () => [
rest.get('*/articles/feed', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetArticlesFeedMock()),
        )
      }),rest.get('*/articles', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetArticlesMock()),
        )
      }),rest.post('*/articles', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getCreateArticleMock()),
        )
      }),rest.get('*/articles/:slug', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetArticleMock()),
        )
      }),rest.put('*/articles/:slug', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getUpdateArticleMock()),
        )
      }),rest.delete('*/articles/:slug', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
        )
      }),]
