import type { Metadata } from 'next';
import ReactQueryProviders from '../lib/ReactQueryProviders';
import { PropsWithChildren } from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="ko">
            <body>
                <ReactQueryProviders>{children}</ReactQueryProviders>
            </body>
        </html>
    );
}
