import './global.css.ts';
import '../../../styles/main.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import RQProvider from 'config/react-query/provider.tsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <RQProvider>
                    <Header />
                    {children}
                    <Footer />
                </RQProvider>
            </body>
        </html>
    );
}
