/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import type {
  TagsResponse
} from '../../models'
import { customInstance } from '../../mutator/custom-instance';



  /**
 * Get tags. Auth not required
 * @summary Get tags
 */
export const getTags = (
    
 ) => {
      return customInstance<TagsResponse>(
      {url: `/tags`, method: 'get'
    },
      );
    }
  
type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

