/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import type { Article } from './article';

export interface MultipleArticlesResponse {
  articles: Article[];
  articlesCount: number;
}
