/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import type { Comment } from './comment';

export interface SingleCommentResponse {
  comment: Comment;
}
