#!/bin/sh

. "$(dirname "$0")/common.sh"
. "$(dirname "$0")/_/husky.sh"

# yarn lint-staged

echo $PATH;

echo 'ESLint 및 Typescript 검증을 시작합니다.';

CHECK_OS="`uname -s`"

case "$CHECK_OS" in
      Darwin*)    THIS_OS=0;;
      Linux*)     THIS_OS=1;;
      MINGW32*)   THIS_OS=2;;
      MINGW64*)   THIS_OS=2;;
      CYGWIN*)    THIS_OS=2;;
esac

if [ $THIS_OS -eq 0 ]
then
  yarn lint:mac || (
    echo 'MAC EsLint 검증에 실패하였습니다.';
    false;
  )
else
  yarn lint || (
    echo 'EsLint 검증에 실패하였습니다.';
    false;
  )
fi

yarn type-check || (
 echo 'Typescript 검증에 실패하였습니다.';
 false;
)